---
# Configures the official Home Assistant frontend.
#
# https://www.home-assistant.io/integrations/frontend/
#
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
  # We can define additional/custom themes for the frontend here.
  themes: !include_dir_merge_named ../../lovelace/themes
