---
# Sensors are a basic platform component in Home Assistant.
# They monitor the states and conditions of a variety of entities.
#
# https://www.home-assistant.io/integrations/sensor/
#
sensor: !include_dir_list ../entities/sensors
