id: living_dark
name: living_dark
entities:

  light.living_ceiling_1:
    state: false
    brightness: 1
    color_mode: color_temp
    color_temp: 454

  light.living_desk_2:
    state: true

  light.living_desk_1:
    state: false
    brightness: 1

  light.living_wall_1:
    state: true
    brightness: 128
    color_mode: "rgb"
    rgb_color:
      - 255
      - 0
      - 0

  switch.living_adaptive_lighting:
    state: false
